In [14]:
#!poetry add -vvv fasttext

In [1]:
import fasttext

In [2]:
ft_vec = fasttext.load_model('/dsdata/models/vec/08_11_3_6_model.bin')

In [3]:
fasttext.

array([ 2.64187574e-01, -3.96591686e-02, -1.13453306e-01, -6.44641757e-01,
       -9.58573297e-02, -5.79610616e-02, -2.31031492e-01, -3.43681335e-01,
       -4.64110784e-02, -4.29249763e-01,  2.03282490e-01, -7.51004100e-01,
       -5.10831140e-02,  5.60059547e-01,  2.27829769e-01, -1.79953784e-01,
        2.81232476e-01, -1.01874493e-01,  8.40672329e-02, -8.03799704e-02,
        2.48819798e-01, -1.98717907e-01,  1.02669775e-01,  5.86590767e-01,
       -1.25891447e-01, -1.61109090e-01,  5.61778963e-01, -1.70828253e-01,
       -2.33085841e-01, -9.86476913e-02,  1.65516108e-01,  3.05378288e-01,
        2.02319920e-01, -1.12731062e-01,  7.19505697e-02, -3.74606043e-01,
        1.59179255e-01,  1.41880125e-01, -4.65173095e-01, -1.61995247e-01,
       -3.32132310e-01,  1.19605981e-01, -9.60481167e-02,  2.32836276e-01,
        2.83962935e-01, -4.07220960e-01, -4.22758430e-01, -2.14150939e-02,
        2.99850479e-02,  1.62375420e-01,  2.42062643e-01,  1.91509008e-01,
        1.91998258e-01, -

In [16]:
ft_vec['помощь'].shape

(300,)

In [18]:
ft_vec['аврыоларвыл'].shape

(300,)

In [20]:
for i,w in enumerate(ft_vec.get_words()):
    print(w)
    if i>10: break

</s>
и
в
на
не
с
что
я
а
по
как
для


In [23]:
ft_vec.get_subwords('помощь')

(['помощь',
  '<по',
  '<пом',
  '<помо',
  '<помощ',
  'пом',
  'помо',
  'помощ',
  'помощь',
  'омо',
  'омощ',
  'омощь',
  'омощь>',
  'мощ',
  'мощь',
  'мощь>',
  'ощь',
  'ощь>',
  'щь>'],
 array([    465, 4072508, 4996768, 4249666, 5422416, 4383922, 5098304,
        4173518, 4459275, 5477493, 4181119, 4936906, 4163212, 4015589,
        5302280, 5026930, 5394932, 5207150, 5338336]))

In [24]:
len(ft_vec.get_words())

3842700

In [27]:
ft_vec.get_input_matrix().shape

(5842700, 300)

In [45]:
import numpy

In [28]:
ft_vec.get_dimension()

300

In [51]:
import numpy

In [54]:
numpy.stack([ft_vec['помоги'], ft_vec['мне']])

array([[-5.43695018e-02,  1.25722261e-02, -1.28469989e-01,
        -4.25097823e-01, -8.03951249e-02, -5.22635728e-02,
         4.04258043e-01, -7.65544325e-02, -6.83326423e-02,
         5.20180836e-02, -2.45018363e-01,  2.33635250e-02,
         7.63228163e-02,  2.75693685e-01,  2.69225687e-01,
         1.23047933e-01,  5.13663709e-01, -4.05032374e-02,
         1.71420887e-01,  2.02293530e-01,  1.25692338e-01,
        -9.98801272e-03,  1.94341868e-01, -9.34438556e-02,
         1.70901179e-01, -2.94895381e-01,  2.65080303e-01,
        -9.01019126e-02, -1.68757215e-01,  3.08078736e-01,
        -3.99354637e-01, -8.66669714e-02, -1.15315400e-01,
        -3.00048161e-02, -9.15682539e-02,  5.78974307e-01,
         2.39713714e-01, -8.15878808e-01, -3.23134631e-01,
        -3.01909391e-02, -1.05718285e-01, -1.37195155e-01,
         7.00061470e-02,  5.11361420e-01,  7.29576200e-02,
        -1.89656734e-01, -4.81621951e-01, -6.65353388e-02,
         1.46592513e-01, -1.76439285e-02, -3.68723482e-0

In [12]:
from spacy._ml import layerize 

@layerize
def DocVectors(docs, drop=0.0):
    batch = []
    for doc in docs:
        vector_list = []
        for token in doc:
            vector_list.append(ft_vec[token.text])
        vectors = numpy.stack(vector_list)
        batch.append(vectors)
    return batch, None


In [13]:
import spacy
nlp=spacy.blank('ru')

In [14]:
doc=nlp('привет вам из леса, мужики!')

In [15]:
r=DocVectors([doc])
type(r),len(r),r[0],r[0].shape

NameError: name 'ft_vec' is not defined

In [17]:
def Tok2Vec(width, embed_size, **kwargs):
    # Circular imports :(
    from spacy._ml import CharacterEmbed, HashEmbed, LN, Maxout, Residual, ExtractWindow, FeatureExtracter
    from spacy._ml import PyTorchBiLSTM
    from spacy.attrs import ID, NORM, PREFIX, SUFFIX, SHAPE, ORTH
    from spacy._ml import Model, chain, clone, concatenate, uniqued, with_flatten

    vectors = kwargs.get("pretrained_vectors", 3)
    cnn_maxout_pieces = kwargs.get("cnn_maxout_pieces", 3)
    conv_depth = kwargs.get("conv_depth", 4)
    bilstm_depth = kwargs.get("bilstm_depth", 0)
    cols = [ID, NORM, PREFIX, SUFFIX, SHAPE, ORTH]
    with Model.define_operators({">>": chain, "|": concatenate, "**": clone}):
        norm = HashEmbed(width, embed_size, column=cols.index(NORM), name="embed_norm")
        prefix = HashEmbed(
            width, embed_size // 2, column=cols.index(PREFIX), name="embed_prefix"
        )
        suffix = HashEmbed(
            width, embed_size // 2, column=cols.index(SUFFIX), name="embed_suffix"
        )
        shape = HashEmbed(
            width, embed_size // 2, column=cols.index(SHAPE), name="embed_shape"
        )
        #glove = numpy.array([1,2,3]) # SpacyVectors()
        vec_width = 300
        
        if vectors is None: 
            embed = uniqued(
                (norm | prefix | suffix | shape)
                >> LN(Maxout(width, width * 4 + vec_width, pieces=3)),
                column=cols.index(ORTH),
            )
        else:
            glove = Vectors(vectors)
            embed = uniqued(
                (vectors | norm | prefix | suffix | shape)
                >> LN(Maxout(width, width * 4 + vec_width, pieces=3)),
                column=cols.index(ORTH),
            )

        convolution = Residual(
            ExtractWindow(nW=1)
            >> LN(Maxout(width, width * 3, pieces=cnn_maxout_pieces))
        )

        tok2vec = FeatureExtracter(cols) >> with_flatten(
            embed >> convolution ** conv_depth, pad=conv_depth
        )

        if bilstm_depth >= 1:
            tok2vec = tok2vec >> PyTorchBiLSTM(width, width, bilstm_depth)
        # Work around thinc API limitations :(. TODO: Revise in Thinc 7
        tok2vec.nO = width
        tok2vec.embed = embed
    return tok2vec
t2v = Tok2Vec(96, 300, pretrained_vectors=ft_vec)


NameError: name 'ft_vec' is not defined

In [16]:
r=t2v([doc])
type(r),len(r),r[0].shape<w

NameError: name 't2v' is not defined

In [19]:
from spacy._ml import FeatureExtracter

In [30]:
docs=[doc, doc]
FeatureExtracter([spacy.attrs.ORTH])(docs)

[array([0, 0, 0, 0, 0, 0, 0], dtype=uint64),
 array([0, 0, 0, 0, 0, 0, 0], dtype=uint64)]

In [29]:
docs[0].vocab.strings[10026568143450433331]

'привет'

In [33]:
from thinc.extra.load_nlp import get_vectors


In [34]:
get_vectors(doc.vocab.vectors.key2row 'ru')

TypeError: get_vectors() missing 1 required positional argument: 'lang'

In [36]:
doc.vocab.vectors??